# Generated by Django 5.2.7 on 2025-10-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxexpress', '0002_initial_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='days_since_last_refill',
        ),
    ]
